#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for Routine Managment
  description: Java + MySQL
  license:
    name: Software Architecture, 2020-I
host: host:8080
basePath: /routine-ms
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /register/routine:
    post:
      summary: Creates a new routine
      operationId: createRoutine
      parameters:
        - name: RegisterRoutinePOJO
          in: body
          required: true
          description: Routine Object for Register
          schema:
            $ref: '#/definitions/RegisterRoutinePOJO'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/RegisterRoutinePOJOErrorModel'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/RegisterRoutinePOJOConflictModel'

  /routine/byIdOwner/{idOwner}:
    get:
      summary: Returns all routines with the given idOwner
      operationId: getUserById
      parameters:
        - name: idOwner
          in: path
          description: The id of the owner of the returned routines
          required: true
          type: integer
      responses:
        '200':
          description: Ok
  /routine/update/{idRoutine}:
    put:
      summary: update the routine specified by the idRoutine
      operationId: updateRoutineById
      parameters:
        - name: idRoutine
          in: path
          description: id of the routine wich is going to update
          required: true
          type: integer
        - name: RegisterRoutinePOJO
          in: body
          required: true
          description: Routine Object for Register
          schema:
            $ref: '#/definitions/RegisterRoutinePOJO'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/RegisterRoutinePOJOErrorModel'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/RegisterRoutinePOJOConflictModel'
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/RegisterRoutinePOJOUnauthorizedModel"
  /routine-ms/routine/getAll:
    get:
      summary: Returns all routines registered
      operationId: getAllRoutine
      responses:
        '200':
          description: Ok
  /routine-ms/routine/getByType/{idType}:
    get:
      summary: Returns all routines from a given type
      operationId: getAllRoutinesByIdType
      parameters:
        - name: idType
          in: path
          required: true
          type: integer
          description: id of the type of routine
      responses:
        '200':
          description: Ok

  /routine-ms/routine/raiting/{idRoutine}:
    put:
      summary: let a user to rate a routine
      operationId: raitingRoutine
      parameters:
        - name: idRoutine
          in: path
          required: true
          type: integer
          description: id of the routine to rate
        - name: RaitingRoutinePOJO
          in: body
          required: true
          description: POJO for rate a routine
          schema:
            $ref: '#/definitions/RegisterRoutinePOJO'

definitions:

  # Users
  User:
    type: object
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
      password:
        type: string

  RegisterRoutinePOJO:
    type: object

    properties:
      idOwner:
        type: integer
        example: 1
      price:
        type: number
      name:
        type: string
      description:
        type: string
      link_preview:
        type: string
      idType:
        type: integer
        example: 1

  UsersList:
    type: object
    required:
      - total
      - list
    properties:
      total:
        type: number
      list:
        type: array
        items:
          $ref: '#/definitions/User'

  # Errors
  RegisterRoutinePOJOErrorModel:
    type: object
    description: the elements of body are null or dont match with their types
    required:
      - idOwner
      - price
      - name
      - description
      - link_preview
      - idType
    properties:
      idOwner:
        type: integer
        example: 1
      price:
        type: number
        example: -2
      name:
        type: object
      description:
        type: string
      link_preview:
        type: string
      idType:
        type: integer
  RegisterRoutinePOJOConflictModel:
    type: object
    description: The type of routine doesnot exist or if you are updating the routine doesnot exist
    required:
      - idOwner
      - price
      - name
      - description
      - link_preview
      - idType
    properties:
      idOwner:
        type: integer
        example: 1
        minimum: 1
      price:
        type: number
        minimun: 0
      name:
        type: string
      description:
        type: string
      link_preview:
        type: string
      idType:
        type: integer
        example: 0
        minimun: 1
  RegisterRoutinePOJOUnauthorizedModel:
    type: object
    description: The user with idOwner is not the routine's owner
    required:
      - idOwner
      - price
      - name
      - description
      - link_preview
      - idType
    properties:
      idOwner:
        type: integer
        example: 0
        minimum: 1
      price:
        type: number
        minimun: 0
      name:
        type: string
      description:
        type: string
      link_preview:
        type: string
      idType:
        type: integer
        example: 0
        minimun: 1