#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for Routine Managment
  description: Java + MySQL
  license:
    name: Software Architecture, 2020-I
host: host:8080
basePath: /routine-ms
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /register/routine:
    post:
      summary: Creates a new routine
      operationId: createRoutine
      parameters:
        - name: RegisterRoutinePOJO
          in: body
          required: true
          description: Routine Object for Register
          schema:
            $ref: '#/definitions/RegisterRoutinePOJO'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/RegisterRoutinePOJOErrorModel'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/RegisterRoutinePOJOConflictModel'

  /users/{id}:
    get:
      summary: Returns an user with the given id
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: The id of the user to be returned
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/User'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
          description: Not Acceptable (Invalid Params)
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'

    put:
      summary: Updates an user with the given id
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: The id of the user to be updated
          required: true
          type: integer
        - name: user
          in: body
          required: true
          description: User Object
          schema:
            $ref: '#/definitions/UserInput'
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
          description: Not Acceptable (Invalid Params)
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'

    delete:
      summary: Deletes an user with the given id
      operationId: deleteCUser
      parameters:
        - name: id
          in: path
          description: The id of the user to be deleted
          required: true
          type: integer
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
          description: Not Acceptable (Invalid Params)
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'

definitions:

  # Users
  User:
    type: object
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
      password:
        type: string

  RegisterRoutinePOJO:
    type: object

    properties:
      idOwner:
        type: integer
        example: 1
      price:
        type: number
      name:
        type: string
      description:
        type: string
      link_preview:
        type: string
      idType:
        type: integer

  UsersList:
    type: object
    required:
      - total
      - list
    properties:
      total:
        type: number
      list:
        type: array
        items:
          $ref: '#/definitions/User'

  # Errors
  RegisterRoutinePOJOErrorModel:
    type: object
    description: the elements of body are null or dont match with their types
    required:
      - idOwner
      - price
      - name
      - description
      - link_preview
      - idType
    properties:
      idOwner:
        type: integer
        example: 1
      price:
        type: number
        example: -2
      name:
        type: object
      description:
        type: string
      link_preview:
        type: string
      idType:
        type: integer
  RegisterRoutinePOJOConflictModel:
    type: object
    description: The type of routine doesnot exist
    required:
      - idOwner
      - price
      - name
      - description
      - link_preview
      - idType
    properties:
      idOwner:
        type: integer
        example: 1
        minimum: 1
      price:
        type: number
        minimun: 0
      name:
        type: string
      description:
        type: string
      link_preview:
        type: string
      idType:
        type: integer
        example: -1
        minimun: 1
