version: '3'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    links:
      - 'mysql-db'

  mysql-db:
    image: 'mysql:5.7'
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_USER=root




