version: "2.1"
networks:
  example-network:
    driver: bridge
services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    networks:
      - example-network
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
  routine-ms:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy

    links:
      - mysql-db
    networks:
      - example-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mydb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      spring.flyway.url: jdbc:mysql://mysql-db:3306/
      spring.flyway.schemas: mydb
      spring.flyway.user: root
      spring.flyway.password: 1234


